services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./.env.server:/app/apps/server/.env
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./.env.client:/app/apps/client/.env
    restart: unless-stopped
